on: 
  push:
    branches-ignore:
      - 'no-ga/**'
  pull_request:
    branches-ignore:
      - 'no-ga/**'

env:
  EXECUTABLES: "compiler"

jobs:
  check_compilation_and_coding_style:
    runs-on: ubuntu-latest
    container: epitechcontent/epitest-docker:latest
    steps:
      - name: fetch files
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: launche banana-check
        run: |
          banana-check-repo
          if ! [ -s "coding-style-reports.log" ]; then
            exit 0
          fi
          exit 1

      - name: compilation
        run: |
          make
          make clean
        timeout-minutes: 2

      - name: check for EXECUTABLES
        shell: bash
        run: |
          export EXEC=${{ env.EXECUTABLES }};
          for index in ${EXEC//,/ };
          do
            if ! [ -x "$index" ]; then
              echo "executable not found"
              exit 1
            fi
          done

  unit_tests:
    needs: [check_compilation_and_coding_style]
    runs-on: ubuntu-latest
    container: epitechcontent/epitest-docker:latest
    steps:
      - name: fetch files
        uses: actions/checkout@v6

      - name: run unit_tests
        run: make tests_run
        timeout-minutes: 2
